/* eslint-disable */
// Generated by locus-codegen. Do not edit by hand.

import Gio from 'gi://Gio?version=2.0';
import GLib from 'gi://GLib?version=2.0';

export type NodeKind =
  | "agent-session"
  | "app-instance"
  | "context"
  | "output"
  | "project"
  | "window"
  | "workspace"
;

export type Relation =
  | "agent-session"
  | "app-instance"
  | "output"
  | "project"
  | "window"
  | "workspace"
;

export type NamedPath =
  | "selected-agent-session"
  | "selected-output"
  | "selected-project"
  | "selected-window"
  | "selected-workspace"
  | "window-agent-session"
;

export type NodeId = string;
export type OptionalNodeId = NodeId | null;
export type Unsubscribe = () => void;

export type NodeSelector =
  | { type: "any" }
  | { type: "kind"; kind: NodeKind | string }
  | { type: "exact"; id: NodeId };

export const locusSchema = {
  nodes: {
    "agent-session": {
      properties: {
        "cwd": { required: false },
        "model": { required: false },
      },
    },
    "app-instance": {
      properties: {
        "icon": { required: false },
        "name": { required: false },
      },
    },
    "context": {
      properties: {
      },
    },
    "output": {
      properties: {
        "connector": { required: false },
        "source": { required: false },
      },
    },
    "project": {
      properties: {
        "icon": { required: false },
        "name": { required: false },
        "path": { required: true },
      },
    },
    "window": {
      properties: {
        "external-id": { required: false },
        "source": { required: false },
      },
    },
    "workspace": {
      properties: {
        "active": { required: false },
        "external-id": { required: false },
        "focused": { required: false },
        "idx": { required: false },
        "name": { required: false },
        "source": { required: false },
        "urgent": { required: false },
      },
    },
  },
  relations: {
    "agent-session": {
      from: { type: "kind", kind: "app-instance" },
      to: { type: "kind", kind: "agent-session" },
      cardinality: "one-to-one",
      retention: "weak",
    },
    "app-instance": {
      from: { type: "kind", kind: "window" },
      to: { type: "kind", kind: "app-instance" },
      cardinality: "one-to-one",
      retention: "weak",
    },
    "output": {
      from: { type: "kind", kind: "workspace" },
      to: { type: "kind", kind: "output" },
      cardinality: "many-to-one",
      retention: "strong",
    },
    "project": {
      from: { type: "kind", kind: "workspace" },
      to: { type: "kind", kind: "project" },
      cardinality: "one-to-one",
      retention: "strong",
    },
    "window": {
      from: { type: "exact", id: "context:selected" },
      to: { type: "kind", kind: "window" },
      cardinality: "many-to-one",
      retention: "strong",
    },
    "workspace": {
      from: { type: "kind", kind: "window" },
      to: { type: "kind", kind: "workspace" },
      cardinality: "many-to-one",
      retention: "strong",
    },
  },
  paths: {
    "selected-agent-session": {
      from: "context:selected",
      path: ["window", "app-instance", "agent-session"],
      many: false,
    },
    "selected-output": {
      from: "context:selected",
      path: ["window", "workspace", "output"],
      many: false,
    },
    "selected-project": {
      from: "context:selected",
      path: ["window", "workspace", "project"],
      many: false,
    },
    "selected-window": {
      from: "context:selected",
      path: ["window"],
      many: false,
    },
    "selected-workspace": {
      from: "context:selected",
      path: ["window", "workspace"],
      many: false,
    },
    "window-agent-session": {
      from: "window",
      path: ["app-instance", "agent-session"],
      many: false,
    },
  },
} as const;

export type PropertyKeyByKind = {
  "agent-session": "cwd" | "model";
  "app-instance": "icon" | "name";
  "context": never;
  "output": "connector" | "source";
  "project": "icon" | "name" | "path";
  "window": "external-id" | "source";
  "workspace": "active" | "external-id" | "focused" | "idx" | "name" | "source" | "urgent";
};

export type PropertyKey = PropertyKeyByKind[NodeKind];

export type LocusClientOptions = {
  traceLatency?: boolean;
};

export type LinkAddedSignal = { type: 'link-added'; source: NodeId; relation: Relation; target: NodeId };
export type LinkRemovedSignal = { type: 'link-removed'; source: NodeId; relation: Relation; target: NodeId };
export type LinkSetSignal = { type: 'link-set'; source: NodeId; relation: Relation; oldTargets: NodeId[]; target: NodeId };
export type PropertyChangedSignal = { type: 'property-changed'; subject: NodeId; key: PropertyKey; value: string };
export type PropertyRemovedSignal = { type: 'property-removed'; subject: NodeId; key: PropertyKey };
export type ResolveChangedSignal = { type: 'resolve-changed'; source: NodeId; path: Relation[]; target: OptionalNodeId };
export type WatchPropertiesUpdatedSignal = { type: 'watch-properties-updated'; changed: Record<string, string>; removed: string[] };

const BUS_NAME = 'io.github.Locus';
const ROOT_PATH = '/io/github/Locus';
const GRAPH_IFACE = 'io.github.Locus.Graph';
const WATCH_IFACE = 'io.github.Locus.Watch';
const PROPERTIES_IFACE = 'org.freedesktop.DBus.Properties';
const NONE = '';

function none(value: string): OptionalNodeId {
  return value.length === 0 ? null : value;
}

function unpackVariant(value: any): any {
  return value && typeof value.deepUnpack === 'function' ? value.deepUnpack() : value;
}

export function samePath(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((part, index) => part === right[index]);
}

export function path(name: NamedPath): { from: NodeId; path: Relation[]; many: boolean } {
  const spec = locusSchema.paths[name];
  return { from: spec.from, path: [...spec.path], many: spec.many };
}

function nowMs(): number {
  return GLib.get_monotonic_time() / 1000;
}

export class LocusWatch {
  constructor(private readonly client: LocusDbusClient, readonly objectPath: string) {}

  async source(): Promise<NodeId> {
    return await this.client.watchProperty(this.objectPath, 'Source') as NodeId;
  }

  async path(): Promise<Relation[]> {
    return await this.client.watchProperty(this.objectPath, 'Path') as Relation[];
  }

  async target(): Promise<OptionalNodeId> {
    return none(await this.client.watchProperty(this.objectPath, 'Target') as string);
  }

  async properties(): Promise<Record<string, string>> {
    return await this.client.watchProperty(this.objectPath, 'Properties') as Record<string, string>;
  }

  async property(key: string): Promise<string> {
    return (await this.properties())[key] ?? '';
  }

  onTargetChanged(handler: (target: OptionalNodeId) => void): Unsubscribe {
    return this.client.onWatchPropertiesChanged(this.objectPath, changed => {
      if (!Object.prototype.hasOwnProperty.call(changed, 'Target')) return;
      handler(none(String(unpackVariant(changed.Target) ?? '')));
    });
  }

  onPropertiesUpdated(handler: (signal: WatchPropertiesUpdatedSignal) => void): Unsubscribe {
    return this.client.onWatchPropertiesUpdated(this.objectPath, handler);
  }

  onPropertyUpdated(key: string, handler: (value: string) => void): Unsubscribe {
    return this.onPropertiesUpdated(signal => {
      if (Object.prototype.hasOwnProperty.call(signal.changed, key)) handler(signal.changed[key] ?? '');
      else if (signal.removed.includes(key)) handler('');
    });
  }

  close(): Promise<void> {
    return this.client.closeWatch(this.objectPath);
  }
}

export class LocusDbusClient {
  private readonly traceLatency: boolean;

  constructor(options: LocusClientOptions = {}) {
    this.traceLatency = options.traceLatency ?? false;
  }

  setLink(source: NodeId, relation: Relation, target: NodeId): Promise<void> {
    return this.callGraph('SetLink', new GLib.Variant('(sss)', [source, relation, target]), null, () => undefined);
  }

  removeLink(source: NodeId, relation: Relation, target: NodeId): Promise<void> {
    return this.callGraph('RemoveLink', new GLib.Variant('(sss)', [source, relation, target]), null, () => undefined);
  }

  removeLinks(source: NodeId, relation: Relation): Promise<void> {
    return this.callGraph('RemoveLinks', new GLib.Variant('(ss)', [source, relation]), null, () => undefined);
  }

  deleteNode(subject: NodeId): Promise<void> {
    return this.callGraph('DeleteNode', new GLib.Variant('(s)', [subject]), null, () => undefined);
  }

  targets(source: NodeId, relation: Relation): Promise<NodeId[]> {
    return this.callGraph('GetTargets', new GLib.Variant('(ss)', [source, relation]), '(as)', ([targets]) => targets as NodeId[]);
  }

  sources(target: NodeId, relation: Relation): Promise<NodeId[]> {
    return this.callGraph('GetSources', new GLib.Variant('(ss)', [target, relation]), '(as)', ([sources]) => sources as NodeId[]);
  }

  setProperty(subject: NodeId, key: PropertyKey, value: string): Promise<void> {
    return this.callGraph('SetProperty', new GLib.Variant('(sss)', [subject, key, value]), null, () => undefined);
  }

  async property(subject: NodeId, key: PropertyKey): Promise<OptionalNodeId> {
    return none(await this.callGraph('GetProperty', new GLib.Variant('(ss)', [subject, key]), '(s)', ([value]) => value as string));
  }

  properties(subject: NodeId): Promise<Record<string, string>> {
    return this.callGraph('GetProperties', new GLib.Variant('(s)', [subject]), '(a{ss})', ([properties]) => properties as Record<string, string>);
  }

  async resolve(source: NodeId, relations: Relation[]): Promise<OptionalNodeId> {
    return none(await this.callGraph('Resolve', new GLib.Variant('(sas)', [source, relations]), '(s)', ([target]) => target as string));
  }

  resolveAll(source: NodeId, relations: Relation[]): Promise<NodeId[]> {
    return this.callGraph('ResolveAll', new GLib.Variant('(sas)', [source, relations]), '(as)', ([targets]) => targets as NodeId[]);
  }

  resolvePath(name: NamedPath, source?: NodeId): Promise<OptionalNodeId> {
    const spec = path(name);
    return this.resolve(source ?? spec.from, spec.path);
  }

  resolveAllPath(name: NamedPath, source?: NodeId): Promise<NodeId[]> {
    const spec = path(name);
    return this.resolveAll(source ?? spec.from, spec.path);
  }

  async subscribeResolve(source: NodeId, relations: Relation[]): Promise<OptionalNodeId> {
    return none(await this.callGraph('SubscribeResolve', new GLib.Variant('(sas)', [source, relations]), '(s)', ([target]) => target as string));
  }

  subscribePath(name: NamedPath, source?: NodeId): Promise<OptionalNodeId> {
    const spec = path(name);
    return this.subscribeResolve(source ?? spec.from, spec.path);
  }

  async watchNode(source: NodeId, relations: Relation[]): Promise<LocusWatch> {
    const objectPath = await this.callGraph('WatchNode', new GLib.Variant('(sas)', [source, relations]), '(o)', ([objectPath]) => objectPath as string);
    return new LocusWatch(this, objectPath);
  }

  watchPath(name: NamedPath, source?: NodeId): Promise<LocusWatch> {
    const spec = path(name);
    return this.watchNode(source ?? spec.from, spec.path);
  }

  onLinkAdded(handler: (signal: LinkAddedSignal) => void): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'LinkAdded', null, null, params => {
      const [source, relation, target] = params.deepUnpack() as [NodeId, Relation, NodeId];
      handler({ type: 'link-added', source, relation, target });
    });
  }

  onLinkRemoved(handler: (signal: LinkRemovedSignal) => void): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'LinkRemoved', null, null, params => {
      const [source, relation, target] = params.deepUnpack() as [NodeId, Relation, NodeId];
      handler({ type: 'link-removed', source, relation, target });
    });
  }

  onLinkSet(handler: (signal: LinkSetSignal) => void): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'LinkSet', null, null, params => {
      const [source, relation, oldTargets, target] = params.deepUnpack() as [NodeId, Relation, NodeId[], NodeId];
      handler({ type: 'link-set', source, relation, oldTargets, target });
    });
  }

  onPropertyChanged(handler: (signal: PropertyChangedSignal) => void): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'PropertyChanged', null, null, params => {
      const [subject, key, value] = params.deepUnpack() as [NodeId, PropertyKey, string];
      handler({ type: 'property-changed', subject, key, value });
    });
  }

  onPropertyRemoved(handler: (signal: PropertyRemovedSignal) => void): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'PropertyRemoved', null, null, params => {
      const [subject, key] = params.deepUnpack() as [NodeId, PropertyKey];
      handler({ type: 'property-removed', subject, key });
    });
  }

  onResolveChanged(handler: (signal: ResolveChangedSignal) => void, source?: NodeId): Unsubscribe {
    return this.subscribeSignal(GRAPH_IFACE, 'ResolveChanged', null, source ?? null, params => {
      const [changedSource, changedPath, target] = params.deepUnpack() as [NodeId, Relation[], string];
      handler({ type: 'resolve-changed', source: changedSource, path: changedPath, target: none(target) });
    });
  }

  watchProperty(objectPath: string, property: 'Source' | 'Path' | 'Target' | 'Properties'): Promise<string | string[] | Record<string, string>> {
    return this.callOn(objectPath, PROPERTIES_IFACE, 'Get', new GLib.Variant('(ss)', [WATCH_IFACE, property]), '(v)', ([value]) => unpackVariant(value));
  }

  onWatchPropertiesChanged(objectPath: string, handler: (changed: Record<string, any>) => void): Unsubscribe {
    return this.subscribeSignal(PROPERTIES_IFACE, 'PropertiesChanged', objectPath, WATCH_IFACE, params => {
      const [iface, changed] = params.deepUnpack() as [string, Record<string, any>, string[]];
      if (iface === WATCH_IFACE) handler(changed);
    });
  }

  onWatchPropertiesUpdated(objectPath: string, handler: (signal: WatchPropertiesUpdatedSignal) => void): Unsubscribe {
    return this.subscribeSignal(WATCH_IFACE, 'PropertiesUpdated', objectPath, null, params => {
      const [changed, removed] = params.deepUnpack() as [Record<string, string>, string[]];
      handler({ type: 'watch-properties-updated', changed, removed });
    });
  }

  closeWatch(objectPath: string): Promise<void> {
    return this.callOn(objectPath, WATCH_IFACE, 'Close', null, null, () => undefined);
  }

  private callGraph<T>(method: string, params: GLib.Variant | null, resultType: string | null, unpack: (result: any) => T): Promise<T> {
    return this.callOn(ROOT_PATH, GRAPH_IFACE, method, params, resultType, unpack);
  }

  private callOn<T>(objectPath: string, iface: string, method: string, params: GLib.Variant | null, resultType: string | null, unpack: (result: any) => T): Promise<T> {
    return new Promise((resolve, reject) => {
      const start = nowMs();
      Gio.DBus.session.call(
        BUS_NAME,
        objectPath,
        iface,
        method,
        params,
        resultType ? new GLib.VariantType(resultType) : null,
        Gio.DBusCallFlags.NONE,
        -1,
        null,
        (_conn: any, res: any) => {
          try {
            const result = Gio.DBus.session.call_finish(res);
            const value = unpack(result.deepUnpack());
            this.logLatency(`${iface}.${method}`, start);
            resolve(value);
          } catch (error) {
            this.logLatency(`${iface}.${method}`, start, true);
            reject(error);
          }
        },
      );
    });
  }

  private subscribeSignal(iface: string, signal: string, objectPath: string | null, arg0: string | null, handler: (params: GLib.Variant) => void): Unsubscribe {
    const id = Gio.DBus.session.signal_subscribe(
      BUS_NAME,
      iface,
      signal,
      objectPath,
      arg0,
      Gio.DBusSignalFlags.NONE,
      (_conn: any, _sender: any, _path: any, _iface: any, _signal: string, params: GLib.Variant) => handler(params),
    );
    return () => Gio.DBus.session.signal_unsubscribe(id);
  }

  private logLatency(method: string, start: number, failed = false): void {
    if (!this.traceLatency) return;
    const elapsed = (nowMs() - start).toFixed(1);
    const status = failed ? ' failed' : '';
    console.log(`[LocusDbus] ${method}${status} +${elapsed}ms`);
  }
}

