/* eslint-disable */
// Generated by locus-codegen. Do not edit by hand.

export type NodeKind =
  | "agent-session"
  | "context"
  | "project"
  | "window"
  | "workspace"
;

export type Relation =
  | "agent-session"
  | "project"
  | "window"
  | "workspace"
;

export type NamedPath =
  | "selected-agent-session"
  | "selected-project"
  | "selected-window"
  | "selected-workspace"
;

export type NodeId = string;
export type OptionalNodeId = NodeId | null;

export type NodeSelector =
  | { type: "any" }
  | { type: "kind"; kind: NodeKind | string }
  | { type: "exact"; id: NodeId };

export const locusSchema = {
  nodes: {
    "agent-session": {
      properties: {
        "cwd": { required: false },
        "model": { required: false },
      },
    },
    "context": {
      properties: {
      },
    },
    "project": {
      properties: {
        "icon": { required: false },
        "name": { required: false },
        "path": { required: true },
      },
    },
    "window": {
      properties: {
        "external-id": { required: false },
        "source": { required: false },
      },
    },
    "workspace": {
      properties: {
        "external-id": { required: false },
        "source": { required: false },
      },
    },
  },
  relations: {
    "agent-session": {
      from: { type: "kind", kind: "window" },
      to: { type: "kind", kind: "agent-session" },
      cardinality: "one-to-one",
    },
    "project": {
      from: { type: "kind", kind: "workspace" },
      to: { type: "kind", kind: "project" },
      cardinality: "one-to-one",
    },
    "window": {
      from: { type: "exact", id: "context:selected" },
      to: { type: "kind", kind: "window" },
      cardinality: "many-to-one",
    },
    "workspace": {
      from: { type: "kind", kind: "window" },
      to: { type: "kind", kind: "workspace" },
      cardinality: "many-to-one",
    },
  },
  paths: {
    "selected-agent-session": {
      from: "context:selected",
      path: ["window", "agent-session"],
    },
    "selected-project": {
      from: "context:selected",
      path: ["window", "workspace", "project"],
    },
    "selected-window": {
      from: "context:selected",
      path: ["window"],
    },
    "selected-workspace": {
      from: "context:selected",
      path: ["window", "workspace"],
    },
  },
} as const;

export interface LocusDbusClient {
  setLink(source: string, relation: string, target: string): Promise<void>;
  removeLink(source: string, relation: string, target: string): Promise<void>;
  getTargets(source: string, relation: string): Promise<string[]>;
  getSources(target: string, relation: string): Promise<string[]>;
  setProperty(subject: string, key: string, value: string): Promise<void>;
  getProperty(subject: string, key: string): Promise<string>;
  getProperties(subject: string): Promise<Record<string, string>>;
  resolve(source: string, path: string[]): Promise<string>;
  resolveAll(source: string, path: string[]): Promise<string[]>;
  subscribeResolve(source: string, path: string[]): Promise<string>;
}

function none(value: string): OptionalNodeId {
  return value.length === 0 ? null : value;
}

export class LocusSchemaClient {
  constructor(private readonly client: LocusDbusClient) {}

  setRelation(source: NodeId, relation: Relation, target: NodeId): Promise<void> {
    return this.client.setLink(source, relation, target);
  }

  removeRelation(source: NodeId, relation: Relation, target: NodeId): Promise<void> {
    return this.client.removeLink(source, relation, target);
  }

  targets(source: NodeId, relation: Relation): Promise<NodeId[]> {
    return this.client.getTargets(source, relation);
  }

  sources(target: NodeId, relation: Relation): Promise<NodeId[]> {
    return this.client.getSources(target, relation);
  }

  setProperty(subject: NodeId, key: string, value: string): Promise<void> {
    return this.client.setProperty(subject, key, value);
  }

  async property(subject: NodeId, key: string): Promise<string | null> {
    return none(await this.client.getProperty(subject, key));
  }

  properties(subject: NodeId): Promise<Record<string, string>> {
    return this.client.getProperties(subject);
  }

  async resolvePath(name: NamedPath): Promise<OptionalNodeId> {
    const spec = locusSchema.paths[name];
    return none(await this.client.resolve(spec.from, [...spec.path]));
  }

  resolveAllPath(name: NamedPath): Promise<NodeId[]> {
    const spec = locusSchema.paths[name];
    return this.client.resolveAll(spec.from, [...spec.path]);
  }

  async subscribePath(name: NamedPath): Promise<OptionalNodeId> {
    const spec = locusSchema.paths[name];
    return none(await this.client.subscribeResolve(spec.from, [...spec.path]));
  }

  selectedAgentSession(): Promise<OptionalNodeId> {
    return this.resolvePath("selected-agent-session");
  }

  subscribeSelectedAgentSession(): Promise<OptionalNodeId> {
    return this.subscribePath("selected-agent-session");
  }

  selectedProject(): Promise<OptionalNodeId> {
    return this.resolvePath("selected-project");
  }

  subscribeSelectedProject(): Promise<OptionalNodeId> {
    return this.subscribePath("selected-project");
  }

  selectedWindow(): Promise<OptionalNodeId> {
    return this.resolvePath("selected-window");
  }

  subscribeSelectedWindow(): Promise<OptionalNodeId> {
    return this.subscribePath("selected-window");
  }

  selectedWorkspace(): Promise<OptionalNodeId> {
    return this.resolvePath("selected-workspace");
  }

  subscribeSelectedWorkspace(): Promise<OptionalNodeId> {
    return this.subscribePath("selected-workspace");
  }

}

