# Generated by locus-codegen. Do not edit by hand.
# Source this file from bash or zsh.

: "${LOCUSCTL:=locusctl}"

locus_resolve() {
  "$LOCUSCTL" resolve "$@"
}

locus_resolve_all() {
  "$LOCUSCTL" resolve-all "$@"
}

locus_prop_get() {
  "$LOCUSCTL" prop get "$@"
}

locus_props() {
  "$LOCUSCTL" prop list "$@"
}

locus_link_targets() {
  "$LOCUSCTL" link targets "$@"
}

locus_link_sources() {
  "$LOCUSCTL" link sources "$@"
}

locus_context_get() {
  "$LOCUSCTL" context get "$@"
}

locus_context_set() {
  "$LOCUSCTL" context set "$@"
}

locus_selected_agent_session() {
  "$LOCUSCTL" resolve 'context:selected' 'window' 'app-instance' 'agent-session'
}

locus_selected_agent_session_all() {
  "$LOCUSCTL" resolve-all 'context:selected' 'window' 'app-instance' 'agent-session'
}

locus_selected_agent_session_prop() {
  local key="${1:?usage: locus_selected_agent_session_prop <key>}"
  local subject
  subject=$(locus_selected_agent_session) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_selected_agent_session_props() {
  local subject
  subject=$(locus_selected_agent_session) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_selected_agent_session_cwd() {
  locus_selected_agent_session_prop 'cwd'
}

locus_selected_agent_session_id() {
  locus_selected_agent_session_prop 'id'
}

locus_selected_agent_session_model() {
  locus_selected_agent_session_prop 'model'
}

locus_selected_output() {
  "$LOCUSCTL" resolve 'context:selected' 'window' 'workspace' 'output'
}

locus_selected_output_all() {
  "$LOCUSCTL" resolve-all 'context:selected' 'window' 'workspace' 'output'
}

locus_selected_output_prop() {
  local key="${1:?usage: locus_selected_output_prop <key>}"
  local subject
  subject=$(locus_selected_output) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_selected_output_props() {
  local subject
  subject=$(locus_selected_output) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_selected_output_connector() {
  locus_selected_output_prop 'connector'
}

locus_selected_output_source() {
  locus_selected_output_prop 'source'
}

locus_selected_project() {
  "$LOCUSCTL" resolve 'context:selected' 'window' 'workspace' 'project'
}

locus_selected_project_all() {
  "$LOCUSCTL" resolve-all 'context:selected' 'window' 'workspace' 'project'
}

locus_selected_project_prop() {
  local key="${1:?usage: locus_selected_project_prop <key>}"
  local subject
  subject=$(locus_selected_project) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_selected_project_props() {
  local subject
  subject=$(locus_selected_project) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_selected_project_icon() {
  locus_selected_project_prop 'icon'
}

locus_selected_project_name() {
  locus_selected_project_prop 'name'
}

locus_selected_project_path() {
  locus_selected_project_prop 'path'
}

locus_selected_window() {
  "$LOCUSCTL" resolve 'context:selected' 'window'
}

locus_selected_window_all() {
  "$LOCUSCTL" resolve-all 'context:selected' 'window'
}

locus_selected_window_prop() {
  local key="${1:?usage: locus_selected_window_prop <key>}"
  local subject
  subject=$(locus_selected_window) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_selected_window_props() {
  local subject
  subject=$(locus_selected_window) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_selected_window_external_id() {
  locus_selected_window_prop 'external-id'
}

locus_selected_window_source() {
  locus_selected_window_prop 'source'
}

locus_selected_workspace() {
  "$LOCUSCTL" resolve 'context:selected' 'window' 'workspace'
}

locus_selected_workspace_all() {
  "$LOCUSCTL" resolve-all 'context:selected' 'window' 'workspace'
}

locus_selected_workspace_prop() {
  local key="${1:?usage: locus_selected_workspace_prop <key>}"
  local subject
  subject=$(locus_selected_workspace) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_selected_workspace_props() {
  local subject
  subject=$(locus_selected_workspace) || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_selected_workspace_active() {
  locus_selected_workspace_prop 'active'
}

locus_selected_workspace_external_id() {
  locus_selected_workspace_prop 'external-id'
}

locus_selected_workspace_focused() {
  locus_selected_workspace_prop 'focused'
}

locus_selected_workspace_idx() {
  locus_selected_workspace_prop 'idx'
}

locus_selected_workspace_name() {
  locus_selected_workspace_prop 'name'
}

locus_selected_workspace_source() {
  locus_selected_workspace_prop 'source'
}

locus_selected_workspace_urgent() {
  locus_selected_workspace_prop 'urgent'
}

locus_window_agent_session() {
  local source="${1:?usage: locus_window_agent_session <source>}"
  "$LOCUSCTL" resolve "$source" 'app-instance' 'agent-session'
}

locus_window_agent_session_all() {
  local source="${1:?usage: locus_window_agent_session_all <source>}"
  "$LOCUSCTL" resolve-all "$source" 'app-instance' 'agent-session'
}

locus_window_agent_session_prop() {
  local source="${1:?usage: locus_window_agent_session_prop <source> <key>}"
  local key="${2:?usage: locus_window_agent_session_prop <source> <key>}"
  local subject
  subject=$("$LOCUSCTL" resolve "$source" 'app-instance' 'agent-session') || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop get "$subject" "$key"
}

locus_window_agent_session_props() {
  local source="${1:?usage: locus_window_agent_session_props <source>}"
  local subject
  subject=$("$LOCUSCTL" resolve "$source" 'app-instance' 'agent-session') || return
  [ -n "$subject" ] || return 1
  "$LOCUSCTL" prop list "$subject"
}

locus_window_agent_session_cwd() {
  locus_window_agent_session_prop "$1" 'cwd'
}

locus_window_agent_session_id() {
  locus_window_agent_session_prop "$1" 'id'
}

locus_window_agent_session_model() {
  locus_window_agent_session_prop "$1" 'model'
}

