KEY_LEFTMETA   1   /home/v47/.config/rsynapse-shell/scripts/super-hints-trigger KEY_LEFTMETA 1
KEY_LEFTMETA   0   /home/v47/.config/rsynapse-shell/scripts/super-hints-trigger KEY_LEFTMETA 0
KEY_RIGHTMETA  1   /home/v47/.config/rsynapse-shell/scripts/super-hints-trigger KEY_RIGHTMETA 1
KEY_RIGHTMETA  0   /home/v47/.config/rsynapse-shell/scripts/super-hints-trigger KEY_RIGHTMETA 0
