KEY_LEFTMETA   1   $HOME/.config/rsynapse-shell/scripts/super-hints-trigger KEY_LEFTMETA 1
KEY_LEFTMETA   0   $HOME/.config/rsynapse-shell/scripts/super-hints-trigger KEY_LEFTMETA 0
KEY_RIGHTMETA  1   $HOME/.config/rsynapse-shell/scripts/super-hints-trigger KEY_RIGHTMETA 1
KEY_RIGHTMETA  0   $HOME/.config/rsynapse-shell/scripts/super-hints-trigger KEY_RIGHTMETA 0
