[[commands]]
pattern = "^todo\\s*(.*)"
command = "Q='$1'; zk list --format jsonl --quiet -m \"TODO/${Q:-*}\" --notebook-dir ~/Notes | jq -c '{id: .absPath, title: .title, description: .lead, command: .absPath}'"
, 
