[plugins."Application Launcher"]
execute = "runapp -- gtk-launch {id}"

[plugins."Calculator"]
execute = "wl-copy -- {data}"

[plugins."Shell Executor"]
execute = "runapp -- {data}"

[plugins."Commands"]
execute = "{data}"

